/*---------------------------------------------------------- 
MASV: 18120397
HO TEN: NGUYEN DANG HONG HUY
LAB: 03 
NGAY: 23/04/2021
----------------------------------------------------------*/ 
USE [QLSV];

CREATE TABLE SINHVIEN
(
	MASV		NVARCHAR(20)	NOT NULL,
	HOTEN		NVARCHAR(100)	NOT NULL, 
	NGAYSINH	DATETIME,
	DIACHI		NVARCHAR(200),
	MALOP		VARCHAR(20), 
	TENDN		NVARCHAR(100)	UNIQUE, 
	MATKHAU		VARBINARY(MAX)		NOT NULL,

	CONSTRAINT PK_SV PRIMARY KEY (MASV)
);


CREATE TABLE NHANVIEN
(
	MANV		VARCHAR(20)		NOT NULL,  
	HOTEN		NVARCHAR(100)	NOT NULL, 
	EMAIL		VARCHAR(20),
	LUONG		VARBINARY(MAX),
	TENDN		NVARCHAR(100)	NOT NULL UNIQUE, 
	MATKHAU		VARBINARY(MAX),

	CONSTRAINT PK_NV PRIMARY KEY (MANV)
);

CREATE TABLE LOP
(
	MALOP		VARCHAR(20)		NOT NULL,  
	TENLOP		NVARCHAR(100)	NOT NULL, 
	MANV		VARCHAR(20),

	CONSTRAINT PK_LO PRIMARY KEY (MALOP)
);

ALTER TABLE SINHVIEN ADD CONSTRAINT FK_SV_LO FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);
ALTER TABLE LOP ADD CONSTRAINT FK_LO_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV);

