/*---------------------------------------------------------- 
MASV: 18120397
HO TEN: NGUYEN DANG HONG HUY
LAB: 03 
NGAY: 23/04/2021
----------------------------------------------------------*/ 
USE [QLSV]
GO

CREATE PROCEDURE SP_LOGIN @USERNAME NVARCHAR(100), @PASSWORD VARCHAR(100)
AS
BEGIN
	DECLARE @MATKHAU VARBINARY(100);
	IF EXISTS (SELECT TENDN FROM DBO.SINHVIEN WHERE TENDN = @USERNAME)
	BEGIN
		SET @MATKHAU = CONVERT(VARBINARY(100),HASHBYTES('MD5', @PASSWORD));
		IF EXISTS (SELECT TENDN FROM DBO.SINHVIEN WHERE TENDN = @USERNAME AND MATKHAU = @MATKHAU)
		BEGIN
			PRINT N'Đăng nhập thành công'
		END
		ELSE
		BEGIN
			RAISERROR(N'Đăng nhập không thành công',16,1)
		END
	END
	ELSE IF EXISTS (SELECT TENDN FROM DBO.NHANVIEN WHERE TENDN = @USERNAME)
	BEGIN
		SET @MATKHAU = CONVERT(VARBINARY(MAX),HASHBYTES('SHA1', @PASSWORD));
		IF EXISTS (SELECT TENDN FROM DBO.NHANVIEN WHERE TENDN = @USERNAME AND MATKHAU = @MATKHAU)
		BEGIN
			PRINT N'Đăng nhập thành công'
		END
		ELSE
		BEGIN
			RAISERROR(N'Đăng nhập không thành công',16,1)
		END
	END
	ELSE
	BEGIN
		RAISERROR( N'Tài khoản không tồn tại',16,1)
	END
END
GO

